apiVersion: v1
kind: Pod
metadata:
  name: config-secret-demo
spec:
  containers:
  - name: demo
    image: busybox
    command: ["/bin/sh", "-c", "env && sleep 3600"]
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: db-secret