apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: busybox
    command: ['sh', '-c', 'while true; do echo "MySQL is running"; sleep 10; done']